-- Updated games table with server-side state
ALTER TABLE games ADD COLUMN IF NOT EXISTS player1_hp INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS player2_hp INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS player1_moves JSONB DEFAULT '[]';
ALTER TABLE games ADD COLUMN IF NOT EXISTS player2_moves JSONB DEFAULT '[]';
ALTER TABLE games ADD COLUMN IF NOT EXISTS player1_ready BOOLEAN DEFAULT FALSE;
ALTER TABLE games ADD COLUMN IF NOT EXISTS player2_ready BOOLEAN DEFAULT FALSE;
ALTER TABLE games ADD COLUMN IF NOT EXISTS current_turn INTEGER DEFAULT 1; -- 1 for player1, 2 for player2
ALTER TABLE games ADD COLUMN IF NOT EXISTS winner_user_id TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS game_log JSONB DEFAULT '[]';